### PR TITLE
fix latencies

### PR DESCRIPTION
**Pull request by tazz4843**
changes *1000 (giving us 1000s of seconds) to /1000 (giving us ms)

### CODE REVIEW

**Comment by hydrostaticcog** [comment]
didn't even give me enough time to review :(

**Comment by tazz4843** [comment]
lmao it's a tiny fix didn't need to review

**Comment by hydrostaticcog** [comment]
yeah ik, i was just bored

**Comment by hydrostaticcog** [comment]
besides it makes my github profile look better by reviewing PRs

**Comment by tazz4843** [comment]
lmfao

**Comment by hydrostaticcog** [comment]
hey man, gotta get s++ rank

**Comment by tazz4843** [comment]
don't you mean F rank?

**Comment by hydrostaticcog** [comment]
uh

**Comment by hydrostaticcog** [comment]
idk, i just know there is some kool rank that i could get if i worked my ass off

**Comment by hydrostaticcog** [comment]
or i could shitpost here

**Comment by tazz4843** [comment]
shitposting will probably get you further

**Comment by hydrostaticcog** [comment]
true

**Comment by hydrostaticcog** [comment]
so, hows it going?

**Comment by tazz4843** [comment]
well as we speak i'm casually breaking chinese law

**Comment by hydrostaticcog** [comment]
oh

**Comment by hydrostaticcog** [comment]
firewall hacking ?

**Comment by tazz4843** [comment]
yup bypassing the GFW

**Comment by tazz4843** [comment]
all this to play Cities: Skylines at not 4fps

**Comment by hydrostaticcog** [comment]
how would that help?

**Comment by tazz4843** [comment]
apparently gaming servers exist in China with absolutely epic GPUs and almost no waiting time
and you can install anything you want on them
you just need to figure out how to bypass the GFW while the entire OS is in Chinese

**Comment by tazz4843** [comment]
shadowsocks exists thankfully so it's basically download one thing and run it bingo bango boom welcome to normal steam instead of chinese steam

**Comment by hydrostaticcog** [comment]
oh nice

**Pull request merged**
